home_index:
    path:     /
    defaults: { _controller: "CoreBundle:Post:index" }
    methods:  GET

home_show:
    path:     /{id}/show
    defaults: { _controller: "CoreBundle:Post:show" }
    methods:  GET

home_new:
    path:     /new
    defaults: { _controller: "CoreBundle:Post:new" }
    methods:  [GET, POST]

home_edit:
    path:     /{id}/edit
    defaults: { _controller: "CoreBundle:Post:edit" }
    methods:  [GET, POST]

home_delete:
    path:     /{id}/delete
    defaults: { _controller: "CoreBundle:Post:delete" }
    methods:  GET
