<?php

namespace CoreBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findbyOrder()
    {
        return $this->createQueryBuilder('a')
            ->where('a.user = :user')
            ->orderBy('a.createdAt', 'DESC');
    }
}